---
name: App-ZofCMS-Plugin-ConfigToTemplate
version: 0.0102
author:
  - "'Zoffix <'zoffix@cpan.org'>"
abstract: plugin to dynamically stuff Main Config File keys into ZofCMS Template
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  App::ZofCMS::Plugin::Base: 0.0103
build_requires:
  Test::More: 0
provides:
  App::ZofCMS::Plugin::ConfigToTemplate:
    file: lib/App/ZofCMS/Plugin/ConfigToTemplate.pm
    version: 0.0102
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
